name: Deploy to vercel staging environment on merge

on:
  push:
    branches:
      - staging
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      
      - uses: dkershner6/vercel-set-env-action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          teamId: ${{ secrets.VERCEL_ORG_ID }}
          projectName: webrep
          envVariableKeys: NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,OPENAI_API_KEY
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          TARGET_NEXT_PUBLIC_SUPABASE_URL: preview,development,production
          TYPE_NEXT_PUBLIC_SUPABASE_URL: encrypted
          
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          TARGET_NEXT_PUBLIC_SUPABASE_ANON_KEY: preview,development,production
          TYPE_NEXT_PUBLIC_SUPABASE_ANON_KEY: encrypted
          
          OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY }}
          TARGET_OPENAI_API_KEY: preview,development,production
          TYPE_OPENAI_API_KEY: encrypted
      
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
