name: Deploy to vercel staging environment on merge

env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY }}

on:
  push:
    branches:
      - staging
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install
      - name: 📤 Pull Vercel Environment Information
        run: pnpm vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: 🏗 Build Project Artifacts
        working-directory: . 
        run: pnpm vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: 🚀 Deploy Project Artifacts to Vercel
        run: |
          pnpm vercel deploy --prebuilt --prod --archive=tgz --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
          pnpm vercel alias --scope=${{ secrets.VERCEL_ORG_ID }} --token=${{ secrets.VERCEL_TOKEN }} set `cat domain.txt` staging.alenta.ai
      - name: preview-url
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}
